io_shaderc.h: add missing `<fstream>` include (#1571)
`gcc-17` cleaned up transitive header inclusion and exposed missing
header as a build failure:

```
In file included from /build/source/libshaderc_util/src/io_shaderc.cc:15:
/build/source/libshaderc_util/include/libshaderc_util/io_shaderc.h:54:31: error: 'std::ofstream' has not been declared
   54 |                               std::ofstream* file_stream, std::ostream* err);
      |                               ^~~
```